name: Generate Streak Stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - name: Generate streak stats image
        uses: DenverCoder1/github-readme-streak-stats@master
        with:
          user_id: LawrenceOtieno
          background: 0A1F44
          ring: 14B8A6
          fire: 14B8A6
          currStreakLabel: 14B8A6
